# Generated by Django 5.1.5 on 2025-01-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("rating", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FINISHED", "Finished"),
                            ("PLAYING", "Playing"),
                            ("PLANTOPLAY", "Plan to Play"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=30,
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("ACTION", "Action"),
                            ("ADVENTURE", "Adventure"),
                            ("RPG", "Role-Playing Game"),
                            ("JRPG", "Japanese Role-Playing Game"),
                            ("STRATEGY", "Strategy"),
                            ("SIMULATION", "Simulation"),
                            ("SPORTS", "Sports"),
                            ("PUZZLE", "Puzzle"),
                            ("HORROR", "Horror"),
                            ("PLATFORMER", "Platformer"),
                            ("SHOOTER", "Shooter"),
                            ("FIGHTING", "Fighting"),
                            ("RACING", "Racing"),
                            ("MMO", "Massively Multiplayer Online (MMO)"),
                            ("SURVIVAL", "Survival"),
                            ("SANDBOX", "Sandbox"),
                            ("STEALTH", "Stealth"),
                            ("MOBA", "Multiplayer Online Battle Arena (MOBA)"),
                            ("RHYTHM", "Rhythm"),
                            ("BATTLE_ROYALE", "Battle Royale"),
                            ("OPEN_WORLD", "Open World"),
                            ("OTHER", "Other"),
                        ],
                        default="Other",
                        max_length=30,
                    ),
                ),
                ("release_date", models.DateField()),
            ],
        ),
    ]
